In [230]:
# Tugas 1 - Basic Python
# Nama  : Oktaviana Sadama Nur Azizah
# NIM   : 24060121130060
# Kelas : Big Data A

In [231]:
# Mencari tau apa itu 'len'
help(len)
len?

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [232]:
# Membuat sebuah list L
L = [1, 2, 3]
L?

# Mencetak list L
print(L)

[1, 2, 3]


In [233]:
# Membuat variabel dengan tipe data berbeda
x1 = 4         # integer
x2 = "empat"   # string

# Mencetak nilai x1 dan x2
print(x1)
print(x2)

4
empat


In [234]:
# Numpy
import numpy
import numpy as np

# Mencetak version numpy
numpy.__version__

'1.25.2'

In [235]:
# Membuat list L dengan range 10
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [236]:
# Mengecek tipe data untuk list L dengan index ke-0
type(L[0])

int

In [237]:
# Menampilkan isi atau nilai dari suatu index dalam list L
print(L[0])
print(L[1])
print(L[5])

0
1
5


In [238]:
# Mengubah tipe data dalam list
L2 = [str(c) for c in L]
print(L2)

# Mencetak tipe data list L2 dengan index ke-0
type(L2[0])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

In [239]:
# Membuat sebuah list yang tipe datanya berbeda-beda
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [240]:
# Membuat array dari numpy
np.array([1, 4, 2, 5, 3])                 # membuat array dari list
np.array([1, 2, 3, 4], dtype='float32')   # menentukan tipe data

array([1., 2., 3., 4.], dtype=float32)

In [241]:
# Generate matriks menggunakan numpy secara random
import numpy as np

np.random.seed(0)
x1 = np.random.randint(10, size=6)          # matriks satu dimensi
x2 = np.random.randint(10, size=(3, 4))     # matriks dua dimensi
x3 = np.random.randint(10, size=(3, 4, 5))  # matriks tiga dimensi

# Mencetak matriks x1, x2, dan x3
print("Matriks x1:")
print(x1)
print()

print("Matriks x2:")
print(x2)
print()

print("Matriks x3:")
print(x3)

# Keterangan
# randint artinya merandom 10 angka

Matriks x1:
[5 0 3 3 7 9]

Matriks x2:
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

Matriks x3:
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [242]:
# Mengecek dimensi matriks 3 dimensi yang sudah dibuat
print("x3 ndim\t:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size\t:", x3.size)

print(x3, "\n")

print("dtype\t:", x3.dtype)

x3 ndim	: 3
x3 shape: (3, 4, 5)
x3 size	: 60
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] 

dtype	: int64


In [243]:
print("Matriks x1")
print(x1)
# Mencetak nilai indeks ke-0 dari matriks x1
print("Indeks-0 dari matriks x1")
print(x1[0], "\n")

print("Matriks x3")
print(x3, "\n")
# Mencetak nilai blok ke-0 dari matriks x3
print("Blok ke-0 dari matriks x3")
print(x3[0], "\n")

# Mencetak nilai indeks ke-0, baris ke-0 dari matriks x3
print("Blok ke-0, baris ke-0 dari matriks x3")
print(x3[0,0])

Matriks x1
[5 0 3 3 7 9]
Indeks-0 dari matriks x1
5 

Matriks x3
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] 

Blok ke-0 dari matriks x3
[[8 1 5 9 8]
 [9 4 3 0 3]
 [5 0 2 3 8]
 [1 3 3 3 7]] 

Blok ke-0, baris ke-0 dari matriks x3
[8 1 5 9 8]


In [244]:
# Slicing atau memecah array satu dimensi
x = np.arange(10)
print(x, "\n")

print(x[:5])    # mencetak array dari awal hingga sebelum elemen ke-5
print(x[5:])    # mencetak array dari elemen ke-5 hingga akhir
print(x[4:7])   # mencetak array dari elemen ke-4 hingga sebelum elemen ke-7
print(x[::2])   # mencetak semua elemen dari awal lompat 2
print(x[::-1])  # mencetak semua elemen dari belakang

[0 1 2 3 4 5 6 7 8 9] 

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [245]:
# Slicing atau memecah array multi dimensi
print("Matriks x2")
print(x2, "\n")

print("Pemecahan 1")
print(x2[:2, :3], "\n")   # mencetak 2 baris awal, 3 kolom awal

print("Pemecahan 2")
print(x2[:, 0], "\n")     # mencetak kolom ke-0

print("Pemecahan 3")
print(x2[0, :])           # mencetak baris ke-0

Matriks x2
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

Pemecahan 1
[[3 5 2]
 [7 6 8]] 

Pemecahan 2
[3 7 1] 

Pemecahan 3
[3 5 2 4]


In [246]:
# Menggabungkan array
x = np.array([1, 2, 3])
y = np.array([6, 7, 8])

# Cara 1
result1 = np.concatenate([x, y])
print(result1)  # 1 dimensi

# Cara 2
result2 = np.array([x, [4, 5, 6]])
print(result2)  # 2 dimensi

[1 2 3 6 7 8]
[[1 2 3]
 [4 5 6]]


In [247]:
# Pemecahan array
x = [1, 2, 3, 99, 99, 3, 2, 1]

x1, x2, x3 = np.split(x, [3, 5])    # pemecahan dilakukan di indeks 3 dan 5.
print(x1, x2, x3)
print(x3)

[1 2 3] [99 99] [3 2 1]
[3 2 1]


In [248]:
# Pemecahan array
grid = np.arange(16).reshape((4, 4))    # dimensi 4x4 sebanyak 16 angka (0-15)
atas, bawah = np.vsplit(grid, [2])      # vertical split menjadi 2

print("Matriks dimensi 4 x 4")
print(grid, "\n")

print("Vertical split atas")
print(atas, "\n")

print("Vertical split bawah")
print(bawah)

Matriks dimensi 4 x 4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

Vertical split atas
[[0 1 2 3]
 [4 5 6 7]] 

Vertical split bawah
[[ 8  9 10 11]
 [12 13 14 15]]


In [249]:
# Pemecahan array
grid = np.arange(16).reshape((4, 4))    # dimensi 4x4 sebanyak 16 angka (0-15)
kiri, kanan = np.hsplit(grid, [2])      # vertical split menjadi 2

print("Matriks dimensi 4 x 4")
print(grid, "\n")

print("Horizontal split kiri")
print(kiri, "\n")

print("Horizontal split kanan")
print(kanan)

Matriks dimensi 4 x 4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

Horizontal split kiri
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

Horizontal split kanan
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
